#!/usr/bin/env bash
# Start all subway servers
# Reads endpoints from packages/networks/src/pet-chain-endpoints.json
# Generates temporary configs from .github/subway-template.yml
#
# Usage:
#   ./start-subway.sh yes    # Append to .env and start servers
#   ./start-subway.sh no     # Skip .env, just start servers

set -e

SUBWAY_BIN=${SUBWAY_BIN:-subway}
TEMPLATE=".github/subway-template.yml"
ENDPOINTS_JSON="packages/networks/src/pet-chain-endpoints.json"
ENV_FILE=".env"

# Parse required positional argument
if [ $# -eq 0 ]; then
  echo "Error: Missing required argument"
  echo ""
  echo "Usage: $0 <yes|no>"
  echo ""
  echo "Arguments:"
  echo "  yes    Append endpoint variables to .env before starting servers"
  echo "  no     Skip .env writing, just start servers"
  exit 1
fi

WRITE_ENV_ARG="$1"

if [ "$WRITE_ENV_ARG" != "yes" ] && [ "$WRITE_ENV_ARG" != "no" ]; then
  echo "Error: Invalid argument '$WRITE_ENV_ARG'"
  echo ""
  echo "Usage: $0 <yes|no>"
  echo ""
  echo "Arguments:"
  echo "  yes    Append endpoint variables to .env before starting servers"
  echo "  no     Skip .env writing, just start servers"
  exit 1
fi

# Check required files exist
if [ ! -f "$TEMPLATE" ]; then
  echo "Error: Template file not found: $TEMPLATE"
  exit 1
fi

if [ ! -f "$ENDPOINTS_JSON" ]; then
  echo "Error: Endpoints file not found: $ENDPOINTS_JSON"
  exit 1
fi

# Check if jq is available
if ! command -v jq &> /dev/null; then
  echo "Error: jq is not installed. Install it with: brew install jq"
  exit 1
fi

# Check if subway is available
if ! command -v "$SUBWAY_BIN" &> /dev/null; then
  echo "Error: subway is not installed or not in PATH"
  echo "Install it with: cargo install --git https://github.com/AcalaNetwork/subway"
  exit 1
fi

# Port mapping
declare -A PORT_MAP=(
  ["polkadot"]=9900
  ["kusama"]=9901
  ["assetHubKusama"]=9902
  ["assetHubPolkadot"]=9903
  ["bridgeHubKusama"]=9904
  ["bridgeHubPolkadot"]=9905
  ["collectivesPolkadot"]=9906
  ["coretimeKusama"]=9907
  ["coretimePolkadot"]=9908
  ["peopleKusama"]=9909
  ["peoplePolkadot"]=9910
  ["encointerKusama"]=9911
  ["acala"]=9912
  ["karura"]=9913
  ["bifrostPolkadot"]=9914
  ["bifrostKusama"]=9915
  ["hydration"]=9916
)

# Append endpoint variables to .env if requested
if [ "$WRITE_ENV_ARG" = "yes" ]; then
  echo "Appending endpoint variables to $ENV_FILE..."

  # Add header if file doesn't exist
  if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'EOF'
# Subway RPC Endpoints
# Generated by start-subway.sh

EOF
  else
    echo "" >> "$ENV_FILE"
    echo "# Subway RPC Endpoints (appended by start-subway.sh)" >> "$ENV_FILE"
  fi

  # Append endpoint variables
  for CHAIN in "${!PORT_MAP[@]}"; do
    PORT=${PORT_MAP[$CHAIN]}
    # Convert camelCase to SCREAMING_SNAKE_CASE
    ENV_VAR=$(echo "$CHAIN" | sed 's/\([A-Z]\)/_\1/g' | tr '[:lower:]' '[:upper:]' | sed 's/^_//')
    echo "${ENV_VAR}_ENDPOINT=ws://127.0.0.1:${PORT}" >> "$ENV_FILE"
  done

  echo "✓ Endpoint variables written to $ENV_FILE"
  echo ""
fi

echo "Starting subway servers..."

# Start subway servers
for CHAIN in "${!PORT_MAP[@]}"; do
  PORT=${PORT_MAP[$CHAIN]}

  # Get endpoints from JSON
  ENDPOINTS=$(jq -c ".$CHAIN" "$ENDPOINTS_JSON")

  if [ "$ENDPOINTS" = "null" ] || [ -z "$ENDPOINTS" ]; then
    echo "  ⚠ Skipping $CHAIN - no endpoints found"
    continue
  fi

  # Generate config from template
  sed -e "s/{{PORT}}/$PORT/g" -e "s|{{ENDPOINTS}}|$ENDPOINTS|g" "$TEMPLATE" > "/tmp/subway-$PORT.yml"

  # Start subway
  $SUBWAY_BIN --config "/tmp/subway-$PORT.yml" > "/tmp/subway-$PORT.log" 2>&1 &
  echo "  ✓ $CHAIN on port $PORT"
done

echo ""
echo "All subway servers started!"
echo "To stop all servers: pkill -f subway"
