#!/usr/bin/env bash
# Start subway servers for specified chains
# Reads endpoints from packages/networks/src/pet-chain-endpoints.json
# Generates temporary configs from .github/subway-template.yml
#
# Usage:
#   ./start-subway.sh <yes|no> [chain port] [chain port] ...
#
# Examples:
#   ./start-subway.sh yes assetHubPolkadot 9001 kusama 9002
#   ./start-subway.sh no polkadot 9000

set -e

SUBWAY_BIN=${SUBWAY_BIN:-subway}
TEMPLATE=".github/subway-template.yml"
ENDPOINTS_JSON="packages/networks/src/pet-chain-endpoints.json"
ENV_FILE=".env"

# Check first argument
if [ $# -eq 0 ]; then
  echo "Error: Missing required argument"
  echo ""
  echo "Usage: $0 <yes|no> [chain port] [chain port] ..."
  echo ""
  echo "Arguments:"
  echo "  yes|no     Append endpoint variables to .env before starting servers"
  echo "  chain      Chain name from pet-chain-endpoints.json (e.g., assetHubPolkadot)"
  echo "  port       Port number for this chain (e.g., 9001)"
  echo ""
  echo "Examples:"
  echo "  $0 yes assetHubPolkadot 9001 kusama 9002"
  echo "  $0 no polkadot 9000"
  exit 1
fi

WRITE_ENV_ARG="$1"
shift

if [ "$WRITE_ENV_ARG" != "yes" ] && [ "$WRITE_ENV_ARG" != "no" ]; then
  echo "Error: First argument must be 'yes' or 'no', got '$WRITE_ENV_ARG'"
  echo ""
  echo "Usage: $0 <yes|no> [chain port] [chain port] ..."
  exit 1
fi

# Check if we have chain/port pairs
if [ $# -eq 0 ]; then
  echo "Error: No chains specified"
  echo ""
  echo "Usage: $0 <yes|no> [chain port] [chain port] ..."
  echo ""
  echo "Examples:"
  echo "  $0 yes assetHubPolkadot 9001 kusama 9002"
  echo "  $0 no polkadot 9000"
  exit 1
fi

# Check arguments come in pairs
if [ $(($# % 2)) -ne 0 ]; then
  echo "Error: Arguments must be chain/port pairs"
  echo "Found $# arguments (expected even number)"
  echo ""
  echo "Usage: $0 <yes|no> [chain port] [chain port] ..."
  exit 1
fi

# Check required files exist
if [ ! -f "$TEMPLATE" ]; then
  echo "Error: Template file not found: $TEMPLATE"
  exit 1
fi

if [ ! -f "$ENDPOINTS_JSON" ]; then
  echo "Error: Endpoints file not found: $ENDPOINTS_JSON"
  exit 1
fi

# Check if jq is available
if ! command -v jq &> /dev/null; then
  echo "Error: jq is not installed. Install it with: brew install jq"
  exit 1
fi

# Check if subway is available
if ! command -v "$SUBWAY_BIN" &> /dev/null; then
  echo "Error: subway is not installed or not in PATH"
  echo "Install it with: cargo install --git https://github.com/AcalaNetwork/subway"
  exit 1
fi

# Collect chain/port pairs for later .env writing if needed
declare -a CHAINS
declare -a PORTS

# Start subway servers
echo "Starting subway servers..."

while [ $# -gt 0 ]; do
  CHAIN="$1"
  PORT="$2"
  shift 2

  # Store for .env writing later
  CHAINS+=("$CHAIN")
  PORTS+=("$PORT")

  # Get endpoints from JSON
  ENDPOINTS=$(jq -c ".$CHAIN" "$ENDPOINTS_JSON")

  if [ "$ENDPOINTS" = "null" ] || [ -z "$ENDPOINTS" ]; then
    echo "Error: No endpoints found for chain '$CHAIN' in $ENDPOINTS_JSON"
    exit 1
  fi

  # Generate config from template
  sed -e "s/{{PORT}}/$PORT/g" -e "s|{{ENDPOINTS}}|$ENDPOINTS|g" "$TEMPLATE" > "/tmp/subway-$PORT.yml"

  # Start subway
  $SUBWAY_BIN --config "/tmp/subway-$PORT.yml" > "/tmp/subway-$PORT.log" 2>&1 &
  echo "  ✓ $CHAIN on port $PORT"
done

echo ""
echo "All subway servers started!"
echo "To stop all servers: pkill -f subway"
echo ""

# Append endpoint variables to .env if requested
if [ "$WRITE_ENV_ARG" = "yes" ]; then
  echo "Appending endpoint variables to $ENV_FILE..."

  # Add header if file doesn't exist
  if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'EOF'
# Subway RPC Endpoints
# Generated by start-subway.sh

EOF
  else
    echo "" >> "$ENV_FILE"
    echo "# Subway RPC Endpoints (appended by start-subway.sh)" >> "$ENV_FILE"
  fi

  # Append endpoint variables for each chain we started
  for i in "${!CHAINS[@]}"; do
    CHAIN="${CHAINS[$i]}"
    PORT="${PORTS[$i]}"

    # Convert camelCase to SCREAMING_SNAKE_CASE
    ENV_VAR=$(echo "$CHAIN" | sed 's/\([A-Z]\)/_\1/g' | tr '[:lower:]' '[:upper:]' | sed 's/^_//')
    echo "${ENV_VAR}_ENDPOINT=ws://127.0.0.1:${PORT}" >> "$ENV_FILE"
  done

  echo "✓ Endpoint variables written to $ENV_FILE"
fi
