/**
 * Constants and expected values for migration testing
 */

export const MIGRATION_CONSTANTS = {
  EXPECTED_INITIAL_PEOPLE_COUNT: 3,

  EXPECTED_CHUNKS_COUNT: 512,

  EXPECTED_DESIGN_FAMILIES_COUNT: 2,

  EXPECTED_GAME_SCHEDULES_COUNT: 15,

  EXPECTED_ONBOARDING_SIZE: 10,

  MAX_MIGRATION_BLOCKS: 30,

  PRIVACY_VOUCHER_VALUE_REFERRED: 80000000000,
  PRIVACY_VOUCHER_VALUE_REFERRER: 20000000000,

  MAX_ON_POLL_BLOCKS: 10,

  EXPECTED_POT_FUNDING_AMOUNT: 1000000,

  MOB_RULE_PAYOUT: {
    AMOUNT_PER_ROUND: 1000,
    COUNT: 10,
    PERIOD_BLOCKS: 100800, // 1 week in blocks (assuming 6 seconds block time)
  },

  SCORE_PAYOUT: {
    AMOUNT_PER_ROUND: 500,
    COUNT: 5,
    DURATION_BLOCKS: 201600, // 2 weeks in blocks (assuming 6 seconds block time)
  },
} as const
