/**
 * Constants and expected values for migration testing
 */

export const MIGRATION_CONSTANTS = {
  EXPECTED_INITIAL_PEOPLE_COUNT: 3,

  EXPECTED_CHUNKS_COUNT: 512,

  EXPECTED_DESIGN_FAMILIES_COUNT: 2,

  EXPECTED_GAME_SCHEDULES_COUNT: 15,

  EXPECTED_ONBOARDING_SIZE: 10,

  MAX_MIGRATION_BLOCKS: 60,

  PRIVACY_VOUCHER_VALUE_REFERRED: 80000000000,
  PRIVACY_VOUCHER_VALUE_REFERRER: 20000000000,
} as const
